// var params = JSON.parse(args.widgetParameter) || {};
var params = {};
var settings = {
  A: "#6CCF64",
  B: "#52A34E",
  C: "#2E6B38",
  D: "#1F432B",
  F: "#171B21",
  year: 2023,
  month: 9,
  goalPoundsPerWeek: 1.5,
  debug: true,
  calendarApp: "calshow",
  backgroundImage: params.bg ? params.bg : "transparent.jpg",
  calFilter: params.calFilter ? params.calFilter : [],
  intensityColor: "",
  widgetBackgroundColor: "#000000",
  todayTextColor: "#000000",
  markToday: true,
  todayCircleColor: "#FFB800",
  showEventCircles: true,
  discountAllDayEvents: false,
  eventCircleColor: "#1E5C7B",
  weekdayTextColor: "#ffffff",
  weekendLetters: "#FFB800",
  weekendLetterOpacity: 1,
  weekendDates: "#FFB800",
  locale: "en-US",
  textColor: "#ffffff",
  eventDateTimeOpacity: 0.7,
  widgetType: params.view ? params.view : "cal",
  showAllDayEvents: true,
  showCalendarBullet: true,
  startWeekOnSunday: false,
  showEventsOnlyForToday: false,
  nextNumOfDays: 7,
  showCompleteTitle: false,
  showPrevMonth: true,
  showNextMonth: true,
  individualDateTargets: false,
  flipped: params.flipped ? params.flipped : false,
};
var settings_default = settings;

module.exports = { settings, settings_default, params };
